version: '3.3'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unbounded-wordpress
      MYSQL_DATABASE: unbounded-wordpress
      MYSQL_USER: unbounded-wordpress
      MYSQL_PASSWORD: unbounded-wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: unbounded-wordpress
      WORDPRESS_DB_PASSWORD: unbounded-wordpress
      WORDPRESS_DB_NAME: unbounded-wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data: {}

